version: '3.8'

services:
  db:
    build:
      context: ..
      dockerfile: docker/Dockerfile-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: server_management
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
